### PR TITLE
introduced poetry

### PR DESCRIPTION
**Pull request by ryantownshend**
I plugged in a pyproject.toml and did some light refactoring. Should simplify setup and usage.

### CODE REVIEW

**Comment by Konfuzian** [comment]
Hey, thanks a lot for your contribution!

However, I am facing an issue with your changes. When I try to run `poetry install`, there is a problem when trying to install mypy:

```
PS C:\Users\sebas\dev\pyspace\theirs\htmx-examples-with-flask> poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing mypy (1.5.1)

  FileNotFoundError

  [Errno 2] No such file or directory: 'C:\\Users\\sebas\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\Local\\pypoetry\\Cache\\virtualenvs\\htmx-examples-with-flask--KWBce_i-py3.11\\Lib\\site-packages\\mypyc\\external\\googletest\\include\\gtest\\internal\\gtest-death-test-internal.h'

  at C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\pathlib.py:1044 in open
      1040│         the built-in open() function does.
      1041│         """
      1042│         if "b" not in mode:
      1043│             encoding = io.text_encoding(encoding)
    → 1044│         return io.open(self, mode, buffering, encoding, errors, newline)
      1045│
      1046│     def read_bytes(self):
      1047│         """
      1048│         Open the file in bytes mode, read it, and close the file.
```

Looks like it uses some package from Google, and that is missing one or more files. I checked the path on my machine, and the whole internal folder is empty...

Totally not your fault, but I cannot merge this until I figure out how to fix that problem. If you have any ideas, let me know.

**Comment by ryantownshend** [comment]
First thing I would try is blow away the generated vm and do a clean `poetry install`

To get the vm folder `poetry env info -p`

**Comment by Konfuzian** [comment]
I tried that, but it didn't fix it. Clearing the poetry cache didn't help either.

I'm gonna try again in a while and see if it works then, otherwise maybe just remove mypy from the dependencies? Python has typing built in nowadays anyway, or is there another use for mypy?

**Comment by Konfuzian** [comment]
Merged, thanks again!

**Pull request merged**
